### PR TITLE
BodoSQL and community blogs are added

### PR DESCRIPTION
**Pull request by nmshafie1993**

### CODE REVIEW

**Comment by njriasan** [comment]
Remove .DS_STORE files and add a git ignore

**Comment by njriasan** [comment]
Do we want to use submodules? It makes the import more confusing. I think we could copy the contents over instead and just link to that folder in the blog post.

**Comment by nmshafie1993** [comment]
> Do we want to use submodules? It makes the import more confusing. I think we could copy the contents over instead and just link to that folder in the blog post.

I made a separate folder for each blog now

**Comment by nmshafie1993** [comment]
> Remove .DS_STORE files and add a git ignore

This is fixed

**Review by njriasan — APPROVED** [review]
LGTM

**Pull request merged**
